## VARIABLES ##
_MAKE_INCLUDE_PATH =../packages/Jagerts.Make/
include $(_MAKE_INCLUDE_PATH)Variables.make

### TARGET VARIABLES ###
TARGET_EXT = $(EXT_SHARED)

### SOURCE VARIABLES ###
INCLUDE_DIRS += 
SRC_FILES += 
LIB_DIRS += 
LIB_FLAGS += $(SHARED_LIB)
LIB_PROJECTS = Jagerts.Felcp.IO Jagerts.Felcp.Imaging

### LANGUAGE VARIABLES ###
COMPILIER = g++
CPP_LANGUAGE = c++1z
PREPROCESSOR_MACROS = 

## RULES ##
include $(_MAKE_INCLUDE_PATH)Rules.make
include $(_MAKE_INCLUDE_PATH)Default-Rules.make